import type { RegionSlug } from './regions';

export type CollegeType =
  | 'research-university'
  | 'liberal-arts'
  | 'institute-of-technology'
  | 'business-school'
  | 'medical-school'
  | 'law-school'
  | 'public-university'
  | 'private-university'
  | 'iit'
  | 'nit'
  | 'iim'
  | 'aiims'
  | 'nlu'
  | 'iisc';

export type CollegeCountry =
  | 'usa'
  | 'canada'
  | 'uk'
  | 'ireland'
  | 'germany'
  | 'france'
  | 'netherlands'
  | 'switzerland'
  | 'sweden'
  | 'denmark'
  | 'italy'
  | 'spain'
  | 'belgium'
  | 'australia'
  | 'new-zealand'
  | 'russia'
  | 'kazakhstan'
  | 'uae'
  | 'qatar'
  | 'saudi-arabia'
  | 'israel'
  | 'singapore'
  | 'hong-kong'
  | 'india';

export type ProgramLevel = 'bachelors' | 'masters' | 'phd' | 'professional';

export interface College {
  id: string;
  slug: string;
  nameEn: string;
  type: CollegeType;
  region: RegionSlug;
  country: CollegeCountry;
  city: string;
  state?: string;
  established: number;
  ranking?: { nirf?: number; qs?: number; the?: number };
  admissionExams: string[];
  applicationPlatform?: string;
  programLevels: ProgramLevel[];
  englishTaught: boolean;
  websiteUrl?: string;
  descriptionEn: string;
  courses: string[];
}

export const COLLEGES: College[] = [
  // ─────────────────────────── USA (20) ───────────────────────────
  {
    id: 'mit',
    slug: 'massachusetts-institute-of-technology',
    nameEn: 'Massachusetts Institute of Technology',
    type: 'institute-of-technology',
    region: 'usa',
    country: 'usa',
    city: 'Cambridge',
    state: 'Massachusetts',
    established: 1861,
    ranking: { qs: 1 },
    admissionExams: ['SAT', 'ACT', 'TOEFL', 'IELTS'],
    applicationPlatform: 'MIT Application (not Common App)',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.mit.edu',
    descriptionEn:
      'MIT is consistently ranked among the world\'s top universities for engineering, computer science, physics, and economics. Admission is highly selective and need-blind for all applicants, including international students. MIT uses its own application portal rather than the Common App.',
    courses: ['Computer Science', 'Engineering', 'Physics', 'Economics', 'Mathematics', 'Architecture'],
  },
  {
    id: 'harvard',
    slug: 'harvard-university',
    nameEn: 'Harvard University',
    type: 'research-university',
    region: 'usa',
    country: 'usa',
    city: 'Cambridge',
    state: 'Massachusetts',
    established: 1636,
    ranking: { qs: 4 },
    admissionExams: ['SAT', 'ACT', 'TOEFL'],
    applicationPlatform: 'Common App / Coalition App',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.harvard.edu',
    descriptionEn:
      'The oldest higher education institution in the United States, Harvard is known for its liberal arts undergraduate program, Harvard Business School, Harvard Law, and Harvard Medical School. Admission is need-blind for U.S. applicants and need-aware (still generous) for international students.',
    courses: ['Liberal Arts', 'Government', 'Economics', 'Law', 'Medicine', 'Business'],
  },
  {
    id: 'stanford',
    slug: 'stanford-university',
    nameEn: 'Stanford University',
    type: 'research-university',
    region: 'usa',
    country: 'usa',
    city: 'Stanford',
    state: 'California',
    established: 1885,
    ranking: { qs: 6 },
    admissionExams: ['SAT', 'ACT', 'TOEFL'],
    applicationPlatform: 'Common App / Coalition App',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.stanford.edu',
    descriptionEn:
      'Stanford sits at the heart of Silicon Valley and is a top destination for computer science, engineering, and business. The Graduate School of Business and School of Engineering are among the most competitive in the world.',
    courses: ['Computer Science', 'Engineering', 'Business', 'Earth Sciences', 'Medicine'],
  },
  {
    id: 'caltech',
    slug: 'california-institute-of-technology',
    nameEn: 'California Institute of Technology',
    type: 'institute-of-technology',
    region: 'usa',
    country: 'usa',
    city: 'Pasadena',
    state: 'California',
    established: 1891,
    ranking: { qs: 10 },
    admissionExams: ['SAT', 'ACT', 'TOEFL'],
    applicationPlatform: 'Common App / Coalition App / QuestBridge',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.caltech.edu',
    descriptionEn:
      'Caltech is a small, intensely research-focused institute with about 1,000 undergraduates. It has produced more Nobel laureates per capita than any other university and operates NASA\'s Jet Propulsion Laboratory.',
    courses: ['Physics', 'Astronomy', 'Engineering', 'Chemistry', 'Biology'],
  },
  {
    id: 'princeton',
    slug: 'princeton-university',
    nameEn: 'Princeton University',
    type: 'research-university',
    region: 'usa',
    country: 'usa',
    city: 'Princeton',
    state: 'New Jersey',
    established: 1746,
    ranking: { qs: 22 },
    admissionExams: ['SAT', 'ACT', 'TOEFL'],
    applicationPlatform: 'Common App / Coalition App / QuestBridge',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.princeton.edu',
    descriptionEn:
      'Princeton emphasizes undergraduate education at the highest level and offers full need-based financial aid to all admitted students, including internationals. Known for mathematics, physics, public and international affairs (SPIA), and the senior thesis tradition.',
    courses: ['Mathematics', 'Physics', 'Economics', 'Public Policy', 'Computer Science'],
  },
  {
    id: 'yale',
    slug: 'yale-university',
    nameEn: 'Yale University',
    type: 'research-university',
    region: 'usa',
    country: 'usa',
    city: 'New Haven',
    state: 'Connecticut',
    established: 1701,
    ranking: { qs: 23 },
    admissionExams: ['SAT', 'ACT', 'TOEFL'],
    applicationPlatform: 'Common App / Coalition App / QuestBridge',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.yale.edu',
    descriptionEn:
      'A founding Ivy with an undergraduate residential college system, Yale is strong across humanities, social sciences, drama, and law. Yale Law School is consistently ranked first in the U.S.',
    courses: ['Humanities', 'Political Science', 'Drama', 'Law', 'History'],
  },
  {
    id: 'columbia',
    slug: 'columbia-university',
    nameEn: 'Columbia University',
    type: 'research-university',
    region: 'usa',
    country: 'usa',
    city: 'New York',
    state: 'New York',
    established: 1754,
    ranking: { qs: 20 },
    admissionExams: ['SAT', 'ACT', 'TOEFL'],
    applicationPlatform: 'Common App / Coalition App / QuestBridge',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.columbia.edu',
    descriptionEn:
      'Located in Morningside Heights, Manhattan, Columbia has the famous Core Curriculum and strong programs in journalism, international affairs, and engineering. It also operates the affiliated Barnard College.',
    courses: ['Engineering', 'Journalism', 'International Affairs', 'Economics', 'Liberal Arts'],
  },
  {
    id: 'upenn',
    slug: 'university-of-pennsylvania',
    nameEn: 'University of Pennsylvania',
    type: 'research-university',
    region: 'usa',
    country: 'usa',
    city: 'Philadelphia',
    state: 'Pennsylvania',
    established: 1740,
    ranking: { qs: 11 },
    admissionExams: ['SAT', 'ACT', 'TOEFL'],
    applicationPlatform: 'Common App / Coalition App / QuestBridge',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.upenn.edu',
    descriptionEn:
      'Penn houses the Wharton School (the first collegiate business school in the U.S.), strong undergraduate programs across four schools, and a tradition of interdisciplinary study via dual-degree programs.',
    courses: ['Business (Wharton)', 'Engineering', 'Nursing', 'Liberal Arts'],
  },
  {
    id: 'uchicago',
    slug: 'university-of-chicago',
    nameEn: 'University of Chicago',
    type: 'research-university',
    region: 'usa',
    country: 'usa',
    city: 'Chicago',
    state: 'Illinois',
    established: 1890,
    ranking: { qs: 21 },
    admissionExams: ['SAT', 'ACT', 'TOEFL'],
    applicationPlatform: 'Common App / Coalition App / QuestBridge',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.uchicago.edu',
    descriptionEn:
      'UChicago is famous for rigorous intellectualism, the Core Curriculum, and producing more Nobel laureates in Economics than any other university. The Booth School of Business is a top-five MBA program globally.',
    courses: ['Economics', 'Mathematics', 'Physics', 'Business (Booth)', 'Social Sciences'],
  },
  {
    id: 'cornell',
    slug: 'cornell-university',
    nameEn: 'Cornell University',
    type: 'research-university',
    region: 'usa',
    country: 'usa',
    city: 'Ithaca',
    state: 'New York',
    established: 1865,
    ranking: { qs: 16 },
    admissionExams: ['SAT', 'ACT', 'TOEFL'],
    applicationPlatform: 'Common App / Coalition App / QuestBridge',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.cornell.edu',
    descriptionEn:
      'The largest Ivy with seven undergraduate colleges, Cornell offers programs from hotel management and agriculture to engineering and architecture. Three of its colleges are statutory (publicly funded for New York residents).',
    courses: ['Engineering', 'Hotel Administration', 'Agriculture', 'Architecture', 'Veterinary Medicine'],
  },
  {
    id: 'brown',
    slug: 'brown-university',
    nameEn: 'Brown University',
    type: 'research-university',
    region: 'usa',
    country: 'usa',
    city: 'Providence',
    state: 'Rhode Island',
    established: 1764,
    ranking: { qs: 64 },
    admissionExams: ['SAT', 'ACT', 'TOEFL'],
    applicationPlatform: 'Common App / Coalition App / QuestBridge',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.brown.edu',
    descriptionEn:
      'Brown is known for the Open Curriculum: students design their own course of study with no distribution requirements. Strong in humanities, computer science, and the Program in Liberal Medical Education (PLME).',
    courses: ['Liberal Arts', 'Computer Science', 'International Relations', 'Medicine (PLME)'],
  },
  {
    id: 'dartmouth',
    slug: 'dartmouth-college',
    nameEn: 'Dartmouth College',
    type: 'research-university',
    region: 'usa',
    country: 'usa',
    city: 'Hanover',
    state: 'New Hampshire',
    established: 1769,
    ranking: { qs: 200 },
    admissionExams: ['SAT', 'ACT', 'TOEFL'],
    applicationPlatform: 'Common App / Coalition App / QuestBridge',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://home.dartmouth.edu',
    descriptionEn:
      'The smallest Ivy, Dartmouth focuses on undergraduate teaching with a quarter-based "D-Plan" calendar. Tuck School of Business is among the top MBA programs. Strong outdoor culture in the New Hampshire woods.',
    courses: ['Liberal Arts', 'Engineering (Thayer)', 'Business (Tuck)', 'Computer Science'],
  },
  {
    id: 'uc-berkeley',
    slug: 'uc-berkeley',
    nameEn: 'University of California, Berkeley',
    type: 'public-university',
    region: 'usa',
    country: 'usa',
    city: 'Berkeley',
    state: 'California',
    established: 1868,
    ranking: { qs: 12 },
    admissionExams: ['SAT', 'ACT', 'TOEFL'],
    applicationPlatform: 'UC Application',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.berkeley.edu',
    descriptionEn:
      'The flagship of the University of California system and top public university in the world. Berkeley is a research powerhouse across CS, engineering, business (Haas), and the sciences. International applicants apply via the UC Application, not the Common App.',
    courses: ['Computer Science', 'Engineering', 'Business (Haas)', 'Economics', 'Letters & Science'],
  },
  {
    id: 'ucla',
    slug: 'ucla',
    nameEn: 'University of California, Los Angeles',
    type: 'public-university',
    region: 'usa',
    country: 'usa',
    city: 'Los Angeles',
    state: 'California',
    established: 1919,
    ranking: { qs: 42 },
    admissionExams: ['SAT', 'ACT', 'TOEFL'],
    applicationPlatform: 'UC Application',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.ucla.edu',
    descriptionEn:
      'UCLA is the most-applied-to university in the United States. Strong across the arts, film (TFT), engineering (Samueli), medicine (Geffen), and the social sciences. Located in Westwood, Los Angeles.',
    courses: ['Film & Television', 'Engineering', 'Psychology', 'Medicine', 'Business Economics'],
  },
  {
    id: 'cmu',
    slug: 'carnegie-mellon-university',
    nameEn: 'Carnegie Mellon University',
    type: 'research-university',
    region: 'usa',
    country: 'usa',
    city: 'Pittsburgh',
    state: 'Pennsylvania',
    established: 1900,
    ranking: { qs: 58 },
    admissionExams: ['SAT', 'ACT', 'TOEFL'],
    applicationPlatform: 'Common App / Coalition App',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.cmu.edu',
    descriptionEn:
      'CMU is the top computer science school in the United States and a leader in robotics, AI, drama (its School of Drama is among the most selective in the world), and design. Cross-disciplinary programs blend technology and the arts.',
    courses: ['Computer Science', 'Robotics', 'Drama', 'Design', 'Engineering', 'Information Systems'],
  },
  {
    id: 'georgia-tech',
    slug: 'georgia-tech',
    nameEn: 'Georgia Institute of Technology',
    type: 'institute-of-technology',
    region: 'usa',
    country: 'usa',
    city: 'Atlanta',
    state: 'Georgia',
    established: 1885,
    ranking: { qs: 80 },
    admissionExams: ['SAT', 'ACT', 'TOEFL'],
    applicationPlatform: 'Common App',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.gatech.edu',
    descriptionEn:
      'A public research institute in Atlanta with top-ranked engineering and computer science programs. Georgia Tech\'s Online Master of Science in Computer Science (OMSCS) is the most affordable accredited CS master\'s in the United States.',
    courses: ['Engineering', 'Computer Science', 'Industrial Design', 'Business'],
  },
  {
    id: 'umich',
    slug: 'university-of-michigan-ann-arbor',
    nameEn: 'University of Michigan, Ann Arbor',
    type: 'public-university',
    region: 'usa',
    country: 'usa',
    city: 'Ann Arbor',
    state: 'Michigan',
    established: 1817,
    ranking: { qs: 44 },
    admissionExams: ['SAT', 'ACT', 'TOEFL'],
    applicationPlatform: 'Common App / Coalition App',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://umich.edu',
    descriptionEn:
      'Michigan is one of the original Public Ivies, with top programs in engineering, business (Ross), public policy (Ford), and information science. Famous for school spirit and a 100,000+ seat football stadium.',
    courses: ['Engineering', 'Business (Ross)', 'Public Policy (Ford)', 'Information', 'Medicine'],
  },
  {
    id: 'northwestern',
    slug: 'northwestern-university',
    nameEn: 'Northwestern University',
    type: 'research-university',
    region: 'usa',
    country: 'usa',
    city: 'Evanston',
    state: 'Illinois',
    established: 1851,
    ranking: { qs: 46 },
    admissionExams: ['SAT', 'ACT', 'TOEFL'],
    applicationPlatform: 'Common App / Coalition App / QuestBridge',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.northwestern.edu',
    descriptionEn:
      'Northwestern is known for journalism (Medill), engineering, theatre (one of the top BFA programs), and the Kellogg School of Management for MBAs. Located on Lake Michigan in suburban Chicago.',
    courses: ['Journalism', 'Engineering', 'Theatre', 'Business (Kellogg)', 'Communication'],
  },
  {
    id: 'duke',
    slug: 'duke-university',
    nameEn: 'Duke University',
    type: 'research-university',
    region: 'usa',
    country: 'usa',
    city: 'Durham',
    state: 'North Carolina',
    established: 1838,
    ranking: { qs: 50 },
    admissionExams: ['SAT', 'ACT', 'TOEFL'],
    applicationPlatform: 'Common App / Coalition App / QuestBridge',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.duke.edu',
    descriptionEn:
      'Duke combines top-tier academics in the Research Triangle of North Carolina with Division I sports. Strong in engineering (Pratt), economics, public policy (Sanford), and medicine (Fuqua MBA is also highly ranked).',
    courses: ['Engineering (Pratt)', 'Economics', 'Public Policy', 'Business (Fuqua)', 'Medicine'],
  },
  {
    id: 'nyu',
    slug: 'new-york-university',
    nameEn: 'New York University',
    type: 'private-university',
    region: 'usa',
    country: 'usa',
    city: 'New York',
    state: 'New York',
    established: 1831,
    ranking: { qs: 35 },
    admissionExams: ['SAT', 'ACT', 'TOEFL'],
    applicationPlatform: 'Common App / Coalition App',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.nyu.edu',
    descriptionEn:
      'NYU has campuses in Manhattan, Abu Dhabi, and Shanghai, plus study-away sites worldwide. Famous for the Stern School of Business, the Tisch School of the Arts (drama, film), and the Tandon School of Engineering.',
    courses: ['Business (Stern)', 'Film & Drama (Tisch)', 'Engineering (Tandon)', 'Liberal Studies'],
  },

  // ─────────────────────────── Canada (8) ───────────────────────────
  {
    id: 'u-toronto',
    slug: 'university-of-toronto',
    nameEn: 'University of Toronto',
    type: 'public-university',
    region: 'canada',
    country: 'canada',
    city: 'Toronto',
    state: 'Ontario',
    established: 1827,
    ranking: { qs: 25 },
    admissionExams: ['IELTS', 'TOEFL', 'Duolingo'],
    applicationPlatform: 'OUAC (Ontario applicants) / direct',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.utoronto.ca',
    descriptionEn:
      'Canada\'s top-ranked university and the largest, U of T has three campuses (St. George, Scarborough, Mississauga) and is a global research leader. Particularly strong in medicine, computer science, and the deep-learning revolution (Geoffrey Hinton).',
    courses: ['Computer Science', 'Medicine', 'Engineering', 'Commerce (Rotman)', 'Arts & Science'],
  },
  {
    id: 'mcgill',
    slug: 'mcgill-university',
    nameEn: 'McGill University',
    type: 'public-university',
    region: 'canada',
    country: 'canada',
    city: 'Montreal',
    state: 'Quebec',
    established: 1821,
    ranking: { qs: 27 },
    admissionExams: ['IELTS', 'TOEFL', 'Duolingo'],
    applicationPlatform: 'Direct via McGill',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.mcgill.ca',
    descriptionEn:
      'English-language research university in Montreal with a strong international student body (about 30%). Notable for medicine, engineering, and management (Desautels). Located in a francophone city, so basic French is useful for daily life.',
    courses: ['Medicine', 'Engineering', 'Management (Desautels)', 'Science', 'Arts'],
  },
  {
    id: 'ubc',
    slug: 'university-of-british-columbia',
    nameEn: 'University of British Columbia',
    type: 'public-university',
    region: 'canada',
    country: 'canada',
    city: 'Vancouver',
    state: 'British Columbia',
    established: 1908,
    ranking: { qs: 38 },
    admissionExams: ['IELTS', 'TOEFL', 'Duolingo'],
    applicationPlatform: 'Direct via UBC',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.ubc.ca',
    descriptionEn:
      'UBC has two campuses (Vancouver and Okanagan) and is known for sustainability research, forestry, computer science, and the Sauder School of Business. Vancouver\'s mild climate and Pacific Rim location are major draws.',
    courses: ['Computer Science', 'Forestry', 'Commerce (Sauder)', 'Engineering', 'Medicine'],
  },
  {
    id: 'waterloo',
    slug: 'university-of-waterloo',
    nameEn: 'University of Waterloo',
    type: 'public-university',
    region: 'canada',
    country: 'canada',
    city: 'Waterloo',
    state: 'Ontario',
    established: 1957,
    ranking: { qs: 115 },
    admissionExams: ['IELTS', 'TOEFL', 'Duolingo'],
    applicationPlatform: 'OUAC',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://uwaterloo.ca',
    descriptionEn:
      'Waterloo runs Canada\'s largest co-op program: students alternate between school and paid internships at companies like Google, Microsoft, and Tesla. The Computer Science and Engineering programs are particularly hard to get into.',
    courses: ['Computer Science', 'Software Engineering', 'Mathematics', 'Engineering'],
  },
  {
    id: 'mcmaster',
    slug: 'mcmaster-university',
    nameEn: 'McMaster University',
    type: 'public-university',
    region: 'canada',
    country: 'canada',
    city: 'Hamilton',
    state: 'Ontario',
    established: 1887,
    ranking: { qs: 189 },
    admissionExams: ['IELTS', 'TOEFL', 'Duolingo'],
    applicationPlatform: 'OUAC',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.mcmaster.ca',
    descriptionEn:
      'McMaster pioneered problem-based learning in medicine and is recognized for the Health Sciences program (one of the most selective undergrad programs in Canada). Strong engineering and business (DeGroote) offerings.',
    courses: ['Health Sciences', 'Engineering', 'Business (DeGroote)', 'Medicine'],
  },
  {
    id: 'queens',
    slug: 'queens-university',
    nameEn: 'Queen\'s University',
    type: 'public-university',
    region: 'canada',
    country: 'canada',
    city: 'Kingston',
    state: 'Ontario',
    established: 1841,
    ranking: { qs: 240 },
    admissionExams: ['IELTS', 'TOEFL', 'Duolingo'],
    applicationPlatform: 'OUAC',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.queensu.ca',
    descriptionEn:
      'A medium-sized university known for the Commerce program (Smith School of Business), engineering, and one of Canada\'s strongest school spirits. Famous tricolour (red, gold, blue) and tradition-rich campus on Lake Ontario.',
    courses: ['Commerce (Smith)', 'Engineering', 'Arts & Science', 'Medicine'],
  },
  {
    id: 'u-alberta',
    slug: 'university-of-alberta',
    nameEn: 'University of Alberta',
    type: 'public-university',
    region: 'canada',
    country: 'canada',
    city: 'Edmonton',
    state: 'Alberta',
    established: 1908,
    ranking: { qs: 113 },
    admissionExams: ['IELTS', 'TOEFL', 'Duolingo'],
    applicationPlatform: 'Direct via UofA',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.ualberta.ca',
    descriptionEn:
      'A leading research university in western Canada, particularly strong in artificial intelligence (home to Amii and DeepMind\'s Edmonton lab), energy, and environmental sciences.',
    courses: ['Computer Science (AI)', 'Engineering', 'Business', 'Medicine'],
  },
  {
    id: 'u-montreal',
    slug: 'university-of-montreal',
    nameEn: 'Université de Montréal',
    type: 'public-university',
    region: 'canada',
    country: 'canada',
    city: 'Montreal',
    state: 'Quebec',
    established: 1878,
    ranking: { qs: 141 },
    admissionExams: ['IELTS', 'TOEFL', 'TCF / TEF (French)'],
    applicationPlatform: 'Direct via UdeM',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: false,
    websiteUrl: 'https://www.umontreal.ca',
    descriptionEn:
      'A francophone research university and the largest French-language university outside France. Top destinations: HEC Montréal (business), Polytechnique Montréal (engineering), and Mila (deep learning, Yoshua Bengio).',
    courses: ['Computer Science (Mila)', 'Business (HEC)', 'Engineering (Polytechnique)', 'Medicine'],
  },

  // ─────────────────────────── UK & Ireland (12) ───────────────────────────
  {
    id: 'oxford',
    slug: 'university-of-oxford',
    nameEn: 'University of Oxford',
    type: 'research-university',
    region: 'uk-ireland',
    country: 'uk',
    city: 'Oxford',
    established: 1096,
    ranking: { qs: 3 },
    admissionExams: ['A-Levels / IB', 'UCAT/BMAT/TSA (subject-specific)', 'IELTS', 'TOEFL'],
    applicationPlatform: 'UCAS',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.ox.ac.uk',
    descriptionEn:
      'The oldest English-speaking university in the world. Oxford uses a tutorial system where students meet weekly in groups of one to three with their tutor. Application includes a written work submission, subject test, and interviews held in December.',
    courses: ['Philosophy, Politics & Economics (PPE)', 'Mathematics', 'Computer Science', 'Medicine', 'Classics', 'Law'],
  },
  {
    id: 'cambridge',
    slug: 'university-of-cambridge',
    nameEn: 'University of Cambridge',
    type: 'research-university',
    region: 'uk-ireland',
    country: 'uk',
    city: 'Cambridge',
    established: 1209,
    ranking: { qs: 5 },
    admissionExams: ['A-Levels / IB', 'STEP / ESAT', 'IELTS', 'TOEFL'],
    applicationPlatform: 'UCAS + My Cambridge Application',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.cam.ac.uk',
    descriptionEn:
      'Cambridge\'s 31 colleges house undergraduates and provide supervisions (Cambridge\'s equivalent of Oxford\'s tutorials). The Mathematical Tripos and Natural Sciences Tripos are particularly famous. Interviews held in December.',
    courses: ['Mathematics', 'Natural Sciences', 'Engineering', 'Computer Science', 'Economics'],
  },
  {
    id: 'imperial',
    slug: 'imperial-college-london',
    nameEn: 'Imperial College London',
    type: 'research-university',
    region: 'uk-ireland',
    country: 'uk',
    city: 'London',
    established: 1907,
    ranking: { qs: 2 },
    admissionExams: ['A-Levels / IB', 'IELTS', 'TOEFL'],
    applicationPlatform: 'UCAS',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.imperial.ac.uk',
    descriptionEn:
      'A STEM-focused university in South Kensington, London. Imperial offers degrees only in science, engineering, medicine, and business — and ranks among the world\'s top universities in each. Heavy industry partnerships with the City of London.',
    courses: ['Engineering', 'Computing', 'Medicine', 'Mathematics', 'Business'],
  },
  {
    id: 'ucl',
    slug: 'university-college-london',
    nameEn: 'University College London',
    type: 'research-university',
    region: 'uk-ireland',
    country: 'uk',
    city: 'London',
    established: 1826,
    ranking: { qs: 9 },
    admissionExams: ['A-Levels / IB', 'IELTS', 'TOEFL'],
    applicationPlatform: 'UCAS',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.ucl.ac.uk',
    descriptionEn:
      'UCL is the largest constituent college of the University of London by enrolment and was the first English university to admit students regardless of religion. Wide subject coverage and a central Bloomsbury location.',
    courses: ['Computer Science', 'Architecture (Bartlett)', 'Economics', 'Medicine', 'Law'],
  },
  {
    id: 'lse',
    slug: 'london-school-of-economics',
    nameEn: 'London School of Economics and Political Science',
    type: 'research-university',
    region: 'uk-ireland',
    country: 'uk',
    city: 'London',
    established: 1895,
    ranking: { qs: 50 },
    admissionExams: ['A-Levels / IB', 'IELTS', 'TOEFL'],
    applicationPlatform: 'UCAS',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.lse.ac.uk',
    descriptionEn:
      'Focused exclusively on social sciences. LSE is a global leader in economics, finance, international relations, and law. Famous alumni include numerous heads of state and Nobel laureates.',
    courses: ['Economics', 'Finance', 'International Relations', 'Law', 'Politics'],
  },
  {
    id: 'edinburgh',
    slug: 'university-of-edinburgh',
    nameEn: 'University of Edinburgh',
    type: 'research-university',
    region: 'uk-ireland',
    country: 'uk',
    city: 'Edinburgh',
    state: 'Scotland',
    established: 1583,
    ranking: { qs: 27 },
    admissionExams: ['A-Levels / IB / Scottish Highers', 'IELTS', 'TOEFL'],
    applicationPlatform: 'UCAS',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.ed.ac.uk',
    descriptionEn:
      'A research-intensive Scottish university with strong programs in AI/informatics, medicine (one of the oldest medical schools in the English-speaking world), and the humanities. Scottish bachelor\'s degrees run four years.',
    courses: ['Informatics (AI)', 'Medicine', 'Philosophy', 'Architecture'],
  },
  {
    id: 'manchester',
    slug: 'university-of-manchester',
    nameEn: 'University of Manchester',
    type: 'research-university',
    region: 'uk-ireland',
    country: 'uk',
    city: 'Manchester',
    established: 2004,
    ranking: { qs: 34 },
    admissionExams: ['A-Levels / IB', 'IELTS', 'TOEFL'],
    applicationPlatform: 'UCAS',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.manchester.ac.uk',
    descriptionEn:
      'The largest single-site university in the UK by enrolment. Manchester has produced 25 Nobel laureates and is strong in engineering, chemistry (where the atom was first split), and biomedical sciences.',
    courses: ['Engineering', 'Chemistry', 'Computer Science', 'Business (Alliance)'],
  },
  {
    id: 'kings-college-london',
    slug: 'kings-college-london',
    nameEn: 'King\'s College London',
    type: 'research-university',
    region: 'uk-ireland',
    country: 'uk',
    city: 'London',
    established: 1829,
    ranking: { qs: 40 },
    admissionExams: ['A-Levels / IB', 'IELTS', 'TOEFL'],
    applicationPlatform: 'UCAS',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.kcl.ac.uk',
    descriptionEn:
      'A constituent college of the University of London with strong programs in medicine, law, war studies, and the humanities. Five campuses across central London including a flagship site on the Strand.',
    courses: ['Medicine', 'Law', 'War Studies', 'Nursing', 'Liberal Arts'],
  },
  {
    id: 'warwick',
    slug: 'university-of-warwick',
    nameEn: 'University of Warwick',
    type: 'research-university',
    region: 'uk-ireland',
    country: 'uk',
    city: 'Coventry',
    established: 1965,
    ranking: { qs: 69 },
    admissionExams: ['A-Levels / IB', 'IELTS', 'TOEFL'],
    applicationPlatform: 'UCAS',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://warwick.ac.uk',
    descriptionEn:
      'A research-focused university with top-ranked Warwick Business School (WBS), strong economics, mathematics, and computer science. Often grouped with Oxbridge and LSE for economics.',
    courses: ['Mathematics', 'Economics', 'Computer Science', 'Business (WBS)'],
  },
  {
    id: 'st-andrews',
    slug: 'university-of-st-andrews',
    nameEn: 'University of St Andrews',
    type: 'research-university',
    region: 'uk-ireland',
    country: 'uk',
    city: 'St Andrews',
    state: 'Scotland',
    established: 1413,
    ranking: { qs: 86 },
    admissionExams: ['A-Levels / IB / Scottish Highers', 'IELTS', 'TOEFL'],
    applicationPlatform: 'UCAS',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.st-andrews.ac.uk',
    descriptionEn:
      'Scotland\'s oldest university and a top-ranked institution in the UK. International student population is one of the highest in the UK. Strong in international relations, philosophy, and physics.',
    courses: ['International Relations', 'Philosophy', 'Physics', 'English Literature'],
  },
  {
    id: 'trinity-college-dublin',
    slug: 'trinity-college-dublin',
    nameEn: 'Trinity College Dublin',
    type: 'research-university',
    region: 'uk-ireland',
    country: 'ireland',
    city: 'Dublin',
    established: 1592,
    ranking: { qs: 87 },
    admissionExams: ['A-Levels / IB / Leaving Cert', 'IELTS', 'TOEFL'],
    applicationPlatform: 'CAO (Ireland) / direct (non-EU)',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.tcd.ie',
    descriptionEn:
      'Ireland\'s oldest university, founded by Queen Elizabeth I. Trinity is known for the humanities, computer science, and the Book of Kells held in its library. Dublin\'s tech industry presence (Google, Meta, LinkedIn HQs) creates strong industry links.',
    courses: ['Computer Science', 'Business (TBS)', 'Medicine', 'Liberal Arts', 'Law'],
  },
  {
    id: 'university-college-dublin',
    slug: 'university-college-dublin',
    nameEn: 'University College Dublin',
    type: 'research-university',
    region: 'uk-ireland',
    country: 'ireland',
    city: 'Dublin',
    established: 1854,
    ranking: { qs: 126 },
    admissionExams: ['A-Levels / IB / Leaving Cert', 'IELTS', 'TOEFL'],
    applicationPlatform: 'CAO (Ireland) / direct (non-EU)',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.ucd.ie',
    descriptionEn:
      'Ireland\'s largest university with strong programs in business (Smurfit School), engineering, and veterinary medicine. Located on a 133-hectare campus in Belfield, south Dublin.',
    courses: ['Business (Smurfit)', 'Engineering', 'Veterinary Medicine', 'Computer Science'],
  },

  // ─────────────────────────── Europe (15) ───────────────────────────
  {
    id: 'eth-zurich',
    slug: 'eth-zurich',
    nameEn: 'ETH Zürich',
    type: 'institute-of-technology',
    region: 'europe',
    country: 'switzerland',
    city: 'Zürich',
    established: 1855,
    ranking: { qs: 7 },
    admissionExams: ['IELTS / TOEFL', 'ETH entrance exam (some)'],
    applicationPlatform: 'Direct via ETH',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://ethz.ch',
    descriptionEn:
      'The Swiss Federal Institute of Technology in Zürich. Bachelor\'s programs taught in German, but most master\'s programs are in English. Alumni include Einstein. Strong in engineering, computer science, and architecture.',
    courses: ['Computer Science', 'Mechanical Engineering', 'Architecture', 'Mathematics', 'Physics'],
  },
  {
    id: 'epfl',
    slug: 'epfl',
    nameEn: 'École Polytechnique Fédérale de Lausanne',
    type: 'institute-of-technology',
    region: 'europe',
    country: 'switzerland',
    city: 'Lausanne',
    established: 1853,
    ranking: { qs: 26 },
    admissionExams: ['IELTS / TOEFL'],
    applicationPlatform: 'Direct via EPFL',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.epfl.ch',
    descriptionEn:
      'Sister institution to ETH Zürich, located on Lake Geneva. Bachelor\'s programs taught in French; master\'s programs in English. Particularly strong in computer science, life sciences, and robotics.',
    courses: ['Computer Science', 'Life Sciences', 'Robotics', 'Engineering'],
  },
  {
    id: 'tu-munich',
    slug: 'tu-munich',
    nameEn: 'Technical University of Munich',
    type: 'institute-of-technology',
    region: 'europe',
    country: 'germany',
    city: 'Munich',
    established: 1868,
    ranking: { qs: 28 },
    admissionExams: ['TestAS / IELTS / TOEFL / German C1'],
    applicationPlatform: 'TUMonline / Uni-Assist',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.tum.de',
    descriptionEn:
      'Germany\'s top technical university and a member of TU9. Bachelor\'s programs mostly in German; master\'s programs increasingly in English. Tuition is low (around €150/semester for state fees plus Munich semester ticket).',
    courses: ['Informatics', 'Mechanical Engineering', 'Electrical Engineering', 'Management (TUM School of Management)'],
  },
  {
    id: 'lmu-munich',
    slug: 'lmu-munich',
    nameEn: 'Ludwig Maximilian University of Munich',
    type: 'research-university',
    region: 'europe',
    country: 'germany',
    city: 'Munich',
    established: 1472,
    ranking: { qs: 59 },
    admissionExams: ['TestAS / IELTS / TOEFL / German C1'],
    applicationPlatform: 'Uni-Assist',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.lmu.de',
    descriptionEn:
      'A leading German research university, particularly strong in physics, philosophy, medicine, and life sciences. Most bachelor\'s programs in German; a growing number of master\'s programs in English.',
    courses: ['Physics', 'Philosophy', 'Medicine', 'Economics', 'Law'],
  },
  {
    id: 'heidelberg',
    slug: 'heidelberg-university',
    nameEn: 'Heidelberg University',
    type: 'research-university',
    region: 'europe',
    country: 'germany',
    city: 'Heidelberg',
    established: 1386,
    ranking: { qs: 84 },
    admissionExams: ['TestAS / IELTS / TOEFL / German C1'],
    applicationPlatform: 'Uni-Assist',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.uni-heidelberg.de',
    descriptionEn:
      'Germany\'s oldest university. Strong reputation in medicine, life sciences, and the humanities. Located in a picturesque Neckar valley town with a romantic old castle and lively student culture.',
    courses: ['Medicine', 'Life Sciences', 'Physics', 'Translation', 'Philosophy'],
  },
  {
    id: 'sorbonne',
    slug: 'sorbonne-university',
    nameEn: 'Sorbonne University',
    type: 'research-university',
    region: 'europe',
    country: 'france',
    city: 'Paris',
    established: 2018,
    ranking: { qs: 41 },
    admissionExams: ['DELF / DALF (French)', 'IELTS / TOEFL'],
    applicationPlatform: 'Campus France / Parcoursup',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.sorbonne-universite.fr',
    descriptionEn:
      'Formed in 2018 from the merger of Pierre and Marie Curie University and Paris-Sorbonne. Three faculties: Arts & Humanities, Science & Engineering, Medicine. Strong in mathematics, physics, and the humanities.',
    courses: ['Mathematics', 'Physics', 'Medicine', 'Literature', 'History'],
  },
  {
    id: 'sciences-po',
    slug: 'sciences-po',
    nameEn: 'Sciences Po',
    type: 'research-university',
    region: 'europe',
    country: 'france',
    city: 'Paris',
    established: 1872,
    ranking: { qs: 319 },
    admissionExams: ['IELTS / TOEFL / French proficiency'],
    applicationPlatform: 'Direct via Sciences Po',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.sciencespo.fr',
    descriptionEn:
      'A specialised social sciences school with seven campuses across France. The Bachelor\'s in Political Humanities and the Paris School of International Affairs (PSIA) attract a global student body. Most undergraduate programs available fully in English.',
    courses: ['Political Science', 'International Affairs', 'Economics', 'Law', 'Public Policy'],
  },
  {
    id: 'tu-delft',
    slug: 'tu-delft',
    nameEn: 'Delft University of Technology',
    type: 'institute-of-technology',
    region: 'europe',
    country: 'netherlands',
    city: 'Delft',
    established: 1842,
    ranking: { qs: 56 },
    admissionExams: ['IELTS / TOEFL'],
    applicationPlatform: 'Studielink',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.tudelft.nl',
    descriptionEn:
      'The largest and oldest Dutch public technical university. Most master\'s programs in English; bachelor\'s in Dutch except Computer Science & Engineering, Aerospace Engineering, Nanobiology, and Applied Earth Sciences which are in English.',
    courses: ['Aerospace Engineering', 'Computer Science', 'Industrial Design', 'Architecture'],
  },
  {
    id: 'university-of-amsterdam',
    slug: 'university-of-amsterdam',
    nameEn: 'University of Amsterdam',
    type: 'research-university',
    region: 'europe',
    country: 'netherlands',
    city: 'Amsterdam',
    established: 1632,
    ranking: { qs: 60 },
    admissionExams: ['IELTS / TOEFL'],
    applicationPlatform: 'Studielink',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.uva.nl',
    descriptionEn:
      'The largest university in the Netherlands with around 30,000 students. Many bachelor\'s programs offered fully in English (Politics, Psychology, Communication, Economics & Business). Strong global outlook.',
    courses: ['Politics, Psychology, Law & Economics (PPLE)', 'Computer Science', 'Economics', 'Communication'],
  },
  {
    id: 'ku-leuven',
    slug: 'ku-leuven',
    nameEn: 'KU Leuven',
    type: 'research-university',
    region: 'europe',
    country: 'belgium',
    city: 'Leuven',
    established: 1425,
    ranking: { qs: 61 },
    admissionExams: ['IELTS / TOEFL'],
    applicationPlatform: 'Direct via KU Leuven',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.kuleuven.be',
    descriptionEn:
      'Belgium\'s top research university and one of the oldest in Europe. Located in a charming Flemish college town. Strong in engineering (imec), biomedical sciences, and humanities. Wide selection of English-taught master\'s programs.',
    courses: ['Engineering', 'Biomedical Sciences', 'Computer Science', 'Philosophy'],
  },
  {
    id: 'kth',
    slug: 'kth-royal-institute',
    nameEn: 'KTH Royal Institute of Technology',
    type: 'institute-of-technology',
    region: 'europe',
    country: 'sweden',
    city: 'Stockholm',
    established: 1827,
    ranking: { qs: 73 },
    admissionExams: ['IELTS / TOEFL'],
    applicationPlatform: 'Universityadmissions.se',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.kth.se',
    descriptionEn:
      'Sweden\'s largest technical university. All master\'s programs taught in English. Free tuition for EU/EEA students; non-EU students pay around SEK 150,000-310,000 per year. Generous scholarship programs.',
    courses: ['Engineering', 'Computer Science', 'Architecture', 'Industrial Engineering'],
  },
  {
    id: 'karolinska',
    slug: 'karolinska-institute',
    nameEn: 'Karolinska Institute',
    type: 'medical-school',
    region: 'europe',
    country: 'sweden',
    city: 'Stockholm',
    established: 1810,
    ranking: { qs: 173 },
    admissionExams: ['IELTS / TOEFL'],
    applicationPlatform: 'Universityadmissions.se',
    programLevels: ['masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://ki.se',
    descriptionEn:
      'One of the world\'s leading medical universities, responsible for selecting the Nobel laureates in Physiology or Medicine. Most master\'s programs are in English; the MD program (Läkarprogrammet) is in Swedish.',
    courses: ['Biomedicine', 'Public Health', 'Bioentrepreneurship', 'Medicine (Swedish)'],
  },
  {
    id: 'bocconi',
    slug: 'bocconi-university',
    nameEn: 'Bocconi University',
    type: 'business-school',
    region: 'europe',
    country: 'italy',
    city: 'Milan',
    established: 1902,
    ranking: { qs: 117 },
    admissionExams: ['Bocconi Test / SAT / IB / IELTS / TOEFL'],
    applicationPlatform: 'Direct via Bocconi',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.unibocconi.eu',
    descriptionEn:
      'Italy\'s top private business and economics university. Most bachelor\'s and master\'s programs in English. Strong placements in European finance, consulting, and tech. The MBA at SDA Bocconi is highly ranked globally.',
    courses: ['Economics', 'Finance', 'Management', 'Data Science'],
  },
  {
    id: 'universidad-complutense',
    slug: 'complutense-university-of-madrid',
    nameEn: 'Complutense University of Madrid',
    type: 'research-university',
    region: 'europe',
    country: 'spain',
    city: 'Madrid',
    established: 1293,
    ranking: { qs: 191 },
    admissionExams: ['DELE (Spanish) / IELTS / TOEFL'],
    applicationPlatform: 'UNEDasiss / direct',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.ucm.es',
    descriptionEn:
      'One of the oldest and largest universities in Spain. Most programs in Spanish but a growing number of master\'s programs in English. Public tuition is among the lowest in Western Europe.',
    courses: ['Law', 'Medicine', 'Economics', 'Communication'],
  },
  {
    id: 'aarhus',
    slug: 'aarhus-university',
    nameEn: 'Aarhus University',
    type: 'research-university',
    region: 'europe',
    country: 'denmark',
    city: 'Aarhus',
    established: 1928,
    ranking: { qs: 142 },
    admissionExams: ['IELTS / TOEFL'],
    applicationPlatform: 'optagelse.dk',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://international.au.dk',
    descriptionEn:
      'Denmark\'s second-largest university with strong research output in life sciences, engineering, business, and humanities. Free tuition for EU/EEA students; non-EU students pay around €8,000-15,000 per year.',
    courses: ['Engineering', 'Business (Aarhus BSS)', 'Molecular Medicine', 'IT Product Development'],
  },

  // ─────────────────────────── Australia & NZ (6) ───────────────────────────
  {
    id: 'u-melbourne',
    slug: 'university-of-melbourne',
    nameEn: 'University of Melbourne',
    type: 'research-university',
    region: 'australia-nz',
    country: 'australia',
    city: 'Melbourne',
    established: 1853,
    ranking: { qs: 13 },
    admissionExams: ['IELTS / TOEFL / PTE'],
    applicationPlatform: 'Direct via Melbourne',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.unimelb.edu.au',
    descriptionEn:
      'Australia\'s top-ranked university. Uses the "Melbourne Model": broad three-year undergraduate degrees followed by specialised graduate study (e.g. JD for law, MD for medicine). A member of the Group of Eight (Go8).',
    courses: ['Commerce', 'Engineering', 'Medicine (Doctor of Medicine)', 'Law (JD)', 'Arts'],
  },
  {
    id: 'u-sydney',
    slug: 'university-of-sydney',
    nameEn: 'University of Sydney',
    type: 'research-university',
    region: 'australia-nz',
    country: 'australia',
    city: 'Sydney',
    established: 1850,
    ranking: { qs: 18 },
    admissionExams: ['IELTS / TOEFL / PTE'],
    applicationPlatform: 'UAC / direct',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.sydney.edu.au',
    descriptionEn:
      'Australia\'s oldest university, founded in 1850. Strong across the humanities, business, engineering, and medicine. Located in the heart of Sydney with a sandstone-and-gargoyle main quadrangle.',
    courses: ['Business', 'Engineering', 'Medicine', 'Veterinary Science', 'Architecture'],
  },
  {
    id: 'unsw',
    slug: 'unsw-sydney',
    nameEn: 'UNSW Sydney',
    type: 'public-university',
    region: 'australia-nz',
    country: 'australia',
    city: 'Sydney',
    established: 1949,
    ranking: { qs: 19 },
    admissionExams: ['IELTS / TOEFL / PTE'],
    applicationPlatform: 'UAC / direct',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.unsw.edu.au',
    descriptionEn:
      'A research-intensive Go8 university with particularly strong engineering, computer science, business (AGSM MBA), and law programs. Trimester-based academic calendar.',
    courses: ['Engineering', 'Computer Science', 'Business (AGSM)', 'Law'],
  },
  {
    id: 'anu',
    slug: 'australian-national-university',
    nameEn: 'Australian National University',
    type: 'research-university',
    region: 'australia-nz',
    country: 'australia',
    city: 'Canberra',
    established: 1946,
    ranking: { qs: 30 },
    admissionExams: ['IELTS / TOEFL / PTE'],
    applicationPlatform: 'Direct via ANU',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.anu.edu.au',
    descriptionEn:
      'Australia\'s national research university, located in the capital, Canberra. Particularly strong in policy, Asia-Pacific studies, physics, and astronomy.',
    courses: ['Public Policy', 'Asia-Pacific Studies', 'Physics', 'Astronomy', 'Law'],
  },
  {
    id: 'u-auckland',
    slug: 'university-of-auckland',
    nameEn: 'University of Auckland',
    type: 'research-university',
    region: 'australia-nz',
    country: 'new-zealand',
    city: 'Auckland',
    established: 1883,
    ranking: { qs: 65 },
    admissionExams: ['IELTS / TOEFL / PTE'],
    applicationPlatform: 'Direct via Auckland',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.auckland.ac.nz',
    descriptionEn:
      'New Zealand\'s largest and highest-ranked university. Strong in business, engineering, and creative arts. International students benefit from a streamlined post-study work visa pathway.',
    courses: ['Business', 'Engineering', 'Computer Science', 'Architecture'],
  },
  {
    id: 'otago',
    slug: 'university-of-otago',
    nameEn: 'University of Otago',
    type: 'research-university',
    region: 'australia-nz',
    country: 'new-zealand',
    city: 'Dunedin',
    established: 1869,
    ranking: { qs: 214 },
    admissionExams: ['IELTS / TOEFL / PTE'],
    applicationPlatform: 'Direct via Otago',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.otago.ac.nz',
    descriptionEn:
      'New Zealand\'s oldest university and the country\'s flagship for medicine and dentistry. Located in Dunedin on the South Island with a strong residential college tradition.',
    courses: ['Medicine', 'Dentistry', 'Health Sciences', 'Marine Science'],
  },

  // ─────────────────────────── Russia & CIS (4) ───────────────────────────
  {
    id: 'msu',
    slug: 'lomonosov-moscow-state-university',
    nameEn: 'Lomonosov Moscow State University',
    type: 'research-university',
    region: 'russia',
    country: 'russia',
    city: 'Moscow',
    established: 1755,
    ranking: { qs: 87 },
    admissionExams: ['Russian language test (TORFL) / IELTS / TOEFL for English-taught'],
    applicationPlatform: 'Direct via MSU / Russia.Study',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.msu.ru',
    descriptionEn:
      'Russia\'s oldest and most prestigious university, founded by Mikhail Lomonosov. Most programs in Russian; an increasing number of English-taught master\'s programs. Open Doors scholarship covers tuition for top international applicants.',
    courses: ['Mathematics', 'Physics', 'Computer Science', 'International Relations'],
  },
  {
    id: 'mipt',
    slug: 'moscow-institute-of-physics-and-technology',
    nameEn: 'Moscow Institute of Physics and Technology',
    type: 'institute-of-technology',
    region: 'russia',
    country: 'russia',
    city: 'Dolgoprudny (near Moscow)',
    established: 1946,
    ranking: { qs: 350 },
    admissionExams: ['MIPT entrance exam / IELTS / TOEFL'],
    applicationPlatform: 'Direct via MIPT',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://mipt.ru',
    descriptionEn:
      'Russia\'s leading institute for physics, mathematics, and theoretical computer science. The "Phystech" tradition combines deep theoretical training with research-lab integration. Several English-taught master\'s in CS, AI, and finance.',
    courses: ['Physics', 'Mathematics', 'Computer Science', 'Applied Mathematics'],
  },
  {
    id: 'hse',
    slug: 'higher-school-of-economics',
    nameEn: 'HSE University',
    type: 'research-university',
    region: 'russia',
    country: 'russia',
    city: 'Moscow',
    established: 1992,
    ranking: { qs: 290 },
    admissionExams: ['HSE Olympiad / IELTS / TOEFL'],
    applicationPlatform: 'Direct via HSE',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.hse.ru',
    descriptionEn:
      'Russia\'s leading social sciences and economics university with campuses in Moscow, St Petersburg, Nizhny Novgorod, and Perm. The largest selection of English-taught programs among Russian universities, including the popular HSE/UoL double degree in Data Science.',
    courses: ['Economics', 'Data Science', 'Politics', 'International Business'],
  },
  {
    id: 'itmo',
    slug: 'itmo-university',
    nameEn: 'ITMO University',
    type: 'institute-of-technology',
    region: 'russia',
    country: 'russia',
    city: 'Saint Petersburg',
    established: 1900,
    ranking: { qs: 360 },
    admissionExams: ['IELTS / TOEFL'],
    applicationPlatform: 'Direct via ITMO',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://en.itmo.ru',
    descriptionEn:
      'A top IT and engineering university known for repeatedly winning the ICPC World Programming Championship. Many English-taught master\'s programs in CS, AI, and photonics.',
    courses: ['Computer Science', 'AI', 'Photonics', 'Software Engineering'],
  },

  // ─────────────────────────── Middle East (5) ───────────────────────────
  {
    id: 'nyu-abu-dhabi',
    slug: 'nyu-abu-dhabi',
    nameEn: 'NYU Abu Dhabi',
    type: 'private-university',
    region: 'middle-east',
    country: 'uae',
    city: 'Abu Dhabi',
    established: 2010,
    ranking: { qs: 261 },
    admissionExams: ['SAT / ACT', 'IELTS / TOEFL'],
    applicationPlatform: 'Common App',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://nyuad.nyu.edu',
    descriptionEn:
      'An NYU portal campus offering a small, highly selective liberal arts and sciences experience. Acceptance rate hovers near 4%. Generous need-based financial aid available to international students, often covering full tuition and travel.',
    courses: ['Liberal Arts', 'Computer Science', 'Engineering', 'Economics'],
  },
  {
    id: 'kaust',
    slug: 'kaust',
    nameEn: 'King Abdullah University of Science and Technology',
    type: 'research-university',
    region: 'middle-east',
    country: 'saudi-arabia',
    city: 'Thuwal',
    established: 2009,
    ranking: { qs: 200 },
    admissionExams: ['IELTS / TOEFL', 'GRE (recommended)'],
    applicationPlatform: 'Direct via KAUST',
    programLevels: ['masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.kaust.edu.sa',
    descriptionEn:
      'A graduate research university on the Red Sea coast offering only master\'s and PhD programs. All admitted students receive a fellowship covering tuition, monthly stipend, housing, and medical insurance.',
    courses: ['Computer Science', 'Bioscience', 'Earth Science', 'Marine Science'],
  },
  {
    id: 'khalifa',
    slug: 'khalifa-university',
    nameEn: 'Khalifa University',
    type: 'research-university',
    region: 'middle-east',
    country: 'uae',
    city: 'Abu Dhabi',
    established: 2007,
    ranking: { qs: 230 },
    admissionExams: ['IELTS / TOEFL', 'SAT (some programs)'],
    applicationPlatform: 'Direct via Khalifa',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.ku.ac.ae',
    descriptionEn:
      'The UAE\'s top-ranked research university, particularly strong in petroleum engineering, aerospace, and AI (home to MBZUAI partnerships). All instruction in English. Generous scholarships available.',
    courses: ['Engineering', 'AI', 'Aerospace', 'Petroleum Engineering'],
  },
  {
    id: 'qatar-university',
    slug: 'qatar-university',
    nameEn: 'Qatar University',
    type: 'public-university',
    region: 'middle-east',
    country: 'qatar',
    city: 'Doha',
    established: 1973,
    ranking: { qs: 173 },
    admissionExams: ['SAT / IELTS / TOEFL'],
    applicationPlatform: 'Direct via QU',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.qu.edu.qa',
    descriptionEn:
      'Qatar\'s national university with the country\'s largest student body. Most undergraduate programs in English (engineering, business, medicine, computing), with some humanities programs in Arabic.',
    courses: ['Engineering', 'Business', 'Medicine', 'Computer Science', 'Islamic Studies'],
  },
  {
    id: 'technion',
    slug: 'technion-israel-institute',
    nameEn: 'Technion — Israel Institute of Technology',
    type: 'institute-of-technology',
    region: 'middle-east',
    country: 'israel',
    city: 'Haifa',
    established: 1912,
    ranking: { qs: 257 },
    admissionExams: ['SAT / Psychometric Entrance Test / IELTS'],
    applicationPlatform: 'Direct via Technion',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.technion.ac.il',
    descriptionEn:
      'Israel\'s oldest university and a global powerhouse in engineering, computer science, and biotechnology. Three alumni have won the Nobel Prize. International students can apply to the English-taught undergraduate International School of Engineering.',
    courses: ['Computer Science', 'Electrical Engineering', 'Biotechnology', 'Aerospace'],
  },

  // ─────────────────────────── India (10) ───────────────────────────
  {
    id: 'iit-bombay',
    slug: 'iit-bombay',
    nameEn: 'Indian Institute of Technology Bombay',
    type: 'iit',
    region: 'india',
    country: 'india',
    city: 'Mumbai',
    state: 'Maharashtra',
    established: 1958,
    ranking: { nirf: 3, qs: 118 },
    admissionExams: ['JEE Advanced'],
    applicationPlatform: 'JoSAA',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.iitb.ac.in',
    descriptionEn:
      'IIT Bombay is one of India\'s premier engineering institutions, known for excellence in technology and research. Located in Powai, Mumbai, it offers undergraduate, postgraduate, and doctoral programs across engineering, sciences, design, and management.',
    courses: ['B.Tech', 'M.Tech', 'M.Sc', 'MBA', 'Ph.D'],
  },
  {
    id: 'iit-delhi',
    slug: 'iit-delhi',
    nameEn: 'Indian Institute of Technology Delhi',
    type: 'iit',
    region: 'india',
    country: 'india',
    city: 'New Delhi',
    state: 'Delhi',
    established: 1961,
    ranking: { nirf: 2, qs: 150 },
    admissionExams: ['JEE Advanced'],
    applicationPlatform: 'JoSAA',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://home.iitd.ac.in',
    descriptionEn:
      'IIT Delhi is a public technical university established in 1961. Located in Hauz Khas, New Delhi, it is one of India\'s top-ranked institutions for engineering and technology, particularly Computer Science and Electrical Engineering.',
    courses: ['B.Tech', 'M.Tech', 'M.Sc', 'MBA', 'Ph.D'],
  },
  {
    id: 'iit-madras',
    slug: 'iit-madras',
    nameEn: 'Indian Institute of Technology Madras',
    type: 'iit',
    region: 'india',
    country: 'india',
    city: 'Chennai',
    state: 'Tamil Nadu',
    established: 1959,
    ranking: { nirf: 1, qs: 227 },
    admissionExams: ['JEE Advanced'],
    applicationPlatform: 'JoSAA',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.iitm.ac.in',
    descriptionEn:
      'IIT Madras has been ranked the No. 1 engineering institution in India by NIRF for multiple consecutive years. Located within a forested campus in Chennai, it is known for research output, industry partnerships, and the IITM BS Data Science program.',
    courses: ['B.Tech', 'M.Tech', 'M.Sc', 'MBA', 'Ph.D', 'B.S Data Science'],
  },
  {
    id: 'iit-kanpur',
    slug: 'iit-kanpur',
    nameEn: 'Indian Institute of Technology Kanpur',
    type: 'iit',
    region: 'india',
    country: 'india',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    established: 1959,
    ranking: { nirf: 4, qs: 278 },
    admissionExams: ['JEE Advanced'],
    applicationPlatform: 'JoSAA',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.iitk.ac.in',
    descriptionEn:
      'IIT Kanpur was the first Indian institution to offer Computer Science education and has a strong reputation for entrepreneurship and research. One of the original five IITs established with foreign collaboration.',
    courses: ['B.Tech', 'M.Tech', 'M.Sc', 'MBA', 'Ph.D'],
  },
  {
    id: 'iit-kharagpur',
    slug: 'iit-kharagpur',
    nameEn: 'Indian Institute of Technology Kharagpur',
    type: 'iit',
    region: 'india',
    country: 'india',
    city: 'Kharagpur',
    state: 'West Bengal',
    established: 1951,
    ranking: { nirf: 5, qs: 271 },
    admissionExams: ['JEE Advanced'],
    applicationPlatform: 'JoSAA',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.iitkgp.ac.in',
    descriptionEn:
      'The oldest IIT, established in 1951. IIT Kharagpur is India\'s largest IIT campus, known for diverse program offerings including law, management, and medical sciences alongside engineering.',
    courses: ['B.Tech', 'Dual Degree', 'M.Tech', 'MBA', 'MCA', 'Ph.D'],
  },
  {
    id: 'nit-trichy',
    slug: 'nit-trichy',
    nameEn: 'National Institute of Technology Tiruchirappalli',
    type: 'nit',
    region: 'india',
    country: 'india',
    city: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    established: 1964,
    ranking: { nirf: 8 },
    admissionExams: ['JEE Main'],
    applicationPlatform: 'JoSAA',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://www.nitt.edu',
    descriptionEn:
      'NIT Trichy is consistently ranked among the top NITs in India. Known for its strong placement record, alumni network across the globe, and a balanced mix of academic rigour with student life.',
    courses: ['B.Tech', 'M.Tech', 'M.Sc', 'MCA', 'Ph.D'],
  },
  {
    id: 'iim-ahmedabad',
    slug: 'iim-ahmedabad',
    nameEn: 'Indian Institute of Management Ahmedabad',
    type: 'iim',
    region: 'india',
    country: 'india',
    city: 'Ahmedabad',
    state: 'Gujarat',
    established: 1961,
    ranking: { nirf: 1 },
    admissionExams: ['CAT'],
    applicationPlatform: 'IIMA admission portal',
    programLevels: ['masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.iima.ac.in',
    descriptionEn:
      'IIM Ahmedabad is India\'s premier management institution and one of the most prestigious business schools in Asia. The flagship Post Graduate Programme (PGP) is widely regarded as equivalent to the best global MBAs.',
    courses: ['PGP (MBA)', 'PGPX', 'FPM (Ph.D)', 'Executive Education'],
  },
  {
    id: 'iim-bangalore',
    slug: 'iim-bangalore',
    nameEn: 'Indian Institute of Management Bangalore',
    type: 'iim',
    region: 'india',
    country: 'india',
    city: 'Bengaluru',
    state: 'Karnataka',
    established: 1973,
    ranking: { nirf: 2 },
    admissionExams: ['CAT'],
    applicationPlatform: 'IIMB admission portal',
    programLevels: ['masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.iimb.ac.in',
    descriptionEn:
      'Located in India\'s technology capital, IIM Bangalore is known for its emphasis on entrepreneurship, public policy, and corporate strategy. Consistently among Asia\'s top-ranked business schools.',
    courses: ['PGP (MBA)', 'PGPEM', 'FPM (Ph.D)', 'Executive Education'],
  },
  {
    id: 'aiims-delhi',
    slug: 'aiims-delhi',
    nameEn: 'All India Institute of Medical Sciences Delhi',
    type: 'aiims',
    region: 'india',
    country: 'india',
    city: 'New Delhi',
    state: 'Delhi',
    established: 1956,
    ranking: { nirf: 1 },
    admissionExams: ['NEET UG', 'NEET PG'],
    applicationPlatform: 'NEET Counselling (MCC)',
    programLevels: ['bachelors', 'masters', 'phd', 'professional'],
    englishTaught: true,
    websiteUrl: 'https://www.aiims.edu',
    descriptionEn:
      'AIIMS Delhi is India\'s most prestigious medical institution, combining cutting-edge research, patient care, and medical education. Admission to the MBBS programme is through NEET UG with a separate merit list.',
    courses: ['MBBS', 'MD', 'MS', 'B.Sc Nursing', 'Ph.D'],
  },
  {
    id: 'nlu-delhi',
    slug: 'nlu-delhi',
    nameEn: 'National Law University Delhi',
    type: 'nlu',
    region: 'india',
    country: 'india',
    city: 'New Delhi',
    state: 'Delhi',
    established: 2008,
    ranking: { nirf: 1 },
    admissionExams: ['AILET'],
    applicationPlatform: 'NLU Delhi AILET portal',
    programLevels: ['bachelors', 'masters', 'phd'],
    englishTaught: true,
    websiteUrl: 'https://nludelhi.ac.in',
    descriptionEn:
      'NLU Delhi is the top-ranked law school in India. Admission is through AILET (All India Law Entrance Test) for its integrated B.A. LL.B. (Hons.) programme. Placement salaries are among the highest for law graduates in India.',
    courses: ['B.A. LL.B. (Hons.)', 'LL.M.', 'Ph.D'],
  },
];

/** Lookup helpers */
export const COLLEGES_BY_TYPE = (type: CollegeType) =>
  COLLEGES.filter((c) => c.type === type);

export const COLLEGES_BY_COUNTRY = (country: CollegeCountry) =>
  COLLEGES.filter((c) => c.country === country);

export const COLLEGES_BY_REGION = (region: string) =>
  COLLEGES.filter((c) => c.region === region);

export const getCollegeBySlug = (slug: string) =>
  COLLEGES.find((c) => c.slug === slug);
