import type { Metadata } from 'next';
import Link from 'next/link';
import { AlertTriangle } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Disclaimer',
  description:
    'Important disclaimer: information on GlobalStudyBoard is for guidance only. Always verify fees, deadlines, rankings and eligibility with the official university or examination website.',
  alternates: { canonical: 'https://www.globalstudyboard.com/disclaimer' },
  openGraph: {
    type: 'website',
    url: 'https://www.globalstudyboard.com/disclaimer',
    title: 'Disclaimer — GlobalStudyBoard',
    description: 'Information on GlobalStudyBoard is for guidance only — always verify with official sources.',
    images: ['/opengraph-image'],
  },
};

const LAST_UPDATED = '22 August 2026';

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="font-display text-2xl font-bold tracking-editorial text-ink">{title}</h2>
      <div className="space-y-3 text-stone-700 leading-relaxed">{children}</div>
    </section>
  );
}

export default function DisclaimerPage() {
  return (
    <div className="max-w-3xl mx-auto space-y-10">
      <header>
        <p className="text-xs font-semibold tracking-[0.22em] uppercase text-stone-500 mb-3">
          Last updated {LAST_UPDATED}
        </p>
        <h1 className="font-display text-4xl md:text-5xl font-bold tracking-editorial leading-[1.08] text-ink mb-5">
          Disclaimer
        </h1>
        <p className="editorial-lede text-stone-800 text-lg leading-relaxed">
          GlobalStudyBoard is an independent, informational resource. Please read this disclaimer
          carefully before relying on anything you find here.
        </p>
      </header>

      <div className="border border-amber-300/70 bg-amber-50 rounded-2xl p-6">
        <div className="flex items-start gap-3">
          <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" aria-hidden="true" />
          <p className="text-stone-800 leading-relaxed m-0">
            <strong>Information provided on GlobalStudyBoard is for guidance only.</strong> Tuition
            fees, application deadlines, rankings, exam patterns and eligibility requirements change
            every academic year. Always verify all details with the official university or
            examination website before applying.
          </p>
        </div>
      </div>

      <Section title="No professional advice">
        <p>
          Nothing on this site is legal, financial, immigration or career advice. Content is general
          information and may not fit your individual circumstances. For decisions that matter,
          consult the relevant official body or a qualified professional.
        </p>
      </Section>

      <Section title="Accuracy &amp; sources">
        <p>
          We aim to base our content on official sources and to link to them so you can verify the
          primary information yourself. Even so, we cannot guarantee that every detail is current,
          complete or error-free at the moment you read it. Where information conflicts, the official
          source always takes precedence over this site.
        </p>
      </Section>

      <Section title="No affiliation">
        <p>
          GlobalStudyBoard is not affiliated with, endorsed by, or sponsored by any university,
          examination board or government agency mentioned on the site. Names and trademarks belong to
          their respective owners and are used for identification only.
        </p>
      </Section>

      <Section title="AI-generated images">
        <p>
          Every image on this site is generated by AI and made to look like a real photograph.
          None of them is one. No image shows a real university, campus, building or city. On a
          page about a particular university, the picture is a general study scene &mdash; a lab or
          an exam hall &mdash; not that campus, and carries no logo or signage. We design and
          review these images to avoid portraying real people. Treat them as decoration, not
          information &mdash; the facts come from the official sources we cite and link.
        </p>
      </Section>

      <Section title="GSB AI responses">
        <p>
          The GSB AI assistant generates answers automatically and may be inaccurate or out of date.
          Use it as a starting point and confirm anything important with official sources.
        </p>
      </Section>

      <Section title="External links &amp; advertising">
        <p>
          The site contains links to third-party websites and may show advertising. We don&rsquo;t
          control and aren&rsquo;t responsible for the content or practices of those external sites.
        </p>
      </Section>

      <Section title="Liability">
        <p>
          To the fullest extent permitted by law, GlobalStudyBoard accepts no liability for any loss
          or inconvenience resulting from reliance on information published here. Your use of the site
          is entirely at your own risk. See also our{' '}
          <Link href="/terms" className="text-forest-700 hover:text-forest-800 underline">
            Terms of Use
          </Link>
          .
        </p>
      </Section>
    </div>
  );
}
